<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mapcss</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>MapCSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#url</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#at_rule_import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#selectors</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>at_rule_import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.mapcss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#url</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.rule.mapcss</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@import)\s*(url\(.*\))\s*(;)</string>
				</dict>
			</array>
		</dict>
		<key>boolean</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.boolean.mapcss</string>
				</dict>
			</array>
		</dict>
		<key>commas</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.entity.mapcss</string>
				</dict>
			</array>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.mapcss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.mapcss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.mapcss</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$\{[^\}]+\}</string>
					<key>name</key>
					<string>constant.other.expression.mapcss</string>
				</dict>
			</array>
		</dict>
		<key>function_regexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.regexp.mapcss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.regexp.modifier.mapcss</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(/.*?/)([a-zA-Z]*)</string>
				</dict>
			</array>
		</dict>
		<key>hex_colors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#(?:[a-fA-F0-9]{3}){1,2}\b</string>
					<key>name</key>
					<string>constant.other.color.mapcss</string>
				</dict>
			</array>
		</dict>
		<key>line</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.line.key.mapcss</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#validator_functions</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#props</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#validator_props</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#word</string>
								</dict>
							</array>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dict.mapcss</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.line.value.mapcss</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#function_regexp</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comparison_operators</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#boolean</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#number</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#hex_colors</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#expressions</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#word</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#ternary</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#commas</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.mapcss</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(.+?)(:) *(.*)(;)(?!.*;)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.mapcss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.period.mapcss</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.set.mapcss</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.mapcss</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(set)\s+(\.?)([\w]+)(;)?</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b-?(?:[0-9]+)(?:\.[0-9]*)?\b</string>
					<key>name</key>
					<string>constant.numeric.mapcss</string>
				</dict>
			</array>
		</dict>
		<key>selector_gut</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commas</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#zoom</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;|&gt;</string>
					<key>name</key>
					<string>keyword.operator.family.mapcss</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.begin.bracket.square.mapcss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\??!?)(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.truthy.mapcss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.end.bracket.square.mapcss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.attribute-selector.mapcss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attribute_selector_guts</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>selectors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_wildcard</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_gut</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comparison_operators</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.period.mapcss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.class.mapcss</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)([a-zA-Z0-9_]+)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selector_not</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.mapcss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.mapcss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.mapcss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<array>
								<string>\\n</string>
								<string>\\r</string>
								<string>\\t</string>
								<string>\\.</string>
								<string>\\"</string>
								<string>\\'</string>
								<string>\\\\</string>
							</array>
							<key>name</key>
							<string>constant.character.escape.mapcss</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.mapcss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.mapcss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.mapcss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<array>
								<string>\\n</string>
								<string>\\r</string>
								<string>\\t</string>
								<string>\\.</string>
								<string>\\'</string>
								<string>\\</string>
							</array>
							<key>name</key>
							<string>constant.character.escape.mapcss</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>word</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_-]*</string>
					<key>name</key>
					<string>meta.word.mapcss</string>
				</dict>
			</array>
		</dict>
		<key>zoom</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\|z)\d+(-)\d+</string>
					<key>name</key>
					<string>keyword.operator.zoom.mapcss</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mapcss</string>
	<key>uuid</key>
	<string>2EC4FCF6-2724-426A-ACE9-FA3B717549CC</string>
</dict>
</plist>
